// Package flags defines environment-scoped boolean flags.
package flags

import (
	"errors"
	"regexp"
	"time"
	"unicode/utf8"
)

var identifierPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9_-]{0,62}$`)

// Flag is identified by the pair (Environment, Key). Timestamps are set by the
// service in UTC. A feature-flag key is a public identifier, not a credential.
type Flag struct {
	Key         string    `json:"key"`
	Environment string    `json:"environment"`
	Description string    `json:"description"`
	Enabled     bool      `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ValidateIdentity checks both identifiers without reflecting user input in
// errors. Restricting their characters also makes environment/key IDs unambiguous.
func ValidateIdentity(environment, key string) error {
	if err := ValidateEnvironment(environment); err != nil {
		return err
	}
	return ValidateKey(key)
}

func ValidateEnvironment(environment string) error {
	if !identifierPattern.MatchString(environment) {
		return errors.New("environment must be 1-63 lowercase ASCII letters, digits, underscores, or hyphens, starting with a letter or digit")
	}
	return nil
}

func ValidateKey(key string) error {
	if !identifierPattern.MatchString(key) {
		return errors.New("key must be 1-63 lowercase ASCII letters, digits, underscores, or hyphens, starting with a letter or digit")
	}
	return nil
}

// CreateInput contains only client-controlled fields. Environment is taken from
// the URL; timestamps are generated by the store.
type CreateInput struct {
	Key         string
	Description string
	Enabled     bool
}

func (input CreateInput) Validate(environment string) error {
	if err := ValidateIdentity(environment, input.Key); err != nil {
		return err
	}
	if !utf8.ValidString(input.Description) || len(input.Description) > 1024 {
		return errors.New("description must be valid UTF-8 and at most 1024 bytes")
	}
	return nil
}
